import "./globals.css";
import { bentonSansPro } from "./fonts";
import ReactQueryProvider from "@/providers/ReactQueryProvider";

export const metadata = {
  title: "Simplyblu BCB | Standard Bank",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={bentonSansPro.variable}>
      <body className={`${bentonSansPro.className} antialiased`}>
        <ReactQueryProvider>{children}</ReactQueryProvider>
      </body>
    </html>
  );
}
